// Generated by CoffeeScript 1.6.3
(function() {
  var DroppableDecorator, droppables,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  droppables = require("./collection");

  DroppableDecorator = (function() {
    /*
    */

    function DroppableDecorator(view) {
      this.view = view;
      this.remove = __bind(this.remove, this);
      this.render = __bind(this.render, this);
      this.name = this.view.droppable;
      this.view.once("render", this.render);
      this.view.once("remove", this.remove);
    }

    /*
    */


    DroppableDecorator.prototype.render = function() {
      return droppables.add(this.name, this);
    };

    /*
    */


    DroppableDecorator.prototype.remove = function() {
      return droppables.remove(this.name, this);
    };

    /*
    */


    DroppableDecorator.priority = "display";

    DroppableDecorator.getOptions = function(view) {
      return view.droppable;
    };

    DroppableDecorator.decorate = function(view, options) {
      return new DroppableDecorator(view, options);
    };

    return DroppableDecorator;

  })();

  module.exports = DroppableDecorator;

}).call(this);
