// Generated by CoffeeScript 1.6.3
(function() {
  var Draggable, Droppable;

  Draggable = require("./draggable");

  Droppable = require("./droppable");

  module.exports = function(app) {
    app.decorator(Draggable);
    return app.decorator(Droppable);
  };

}).call(this);
